//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLfriend.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy.json")]
        public string ThemeFile {
            get {
                return ((string)(this["ThemeFile"]));
            }
            set {
                this["ThemeFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] CharacterReferenceSettingStatus {
            get {
                return ((int[])(this["CharacterReferenceSettingStatus"]));
            }
            set {
                this["CharacterReferenceSettingStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CharacterReferenceSettingSymbol {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CharacterReferenceSettingSymbol"]));
            }
            set {
                this["CharacterReferenceSettingSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CharacterReferenceSettingText {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CharacterReferenceSettingText"]));
            }
            set {
                this["CharacterReferenceSettingText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumberOfTimesToRemoveDoubleSpaces {
            get {
                return ((int)(this["NumberOfTimesToRemoveDoubleSpaces"]));
            }
            set {
                this["NumberOfTimesToRemoveDoubleSpaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunDoubleSpaceRemovalAdditionalTimes {
            get {
                return ((bool)(this["RunDoubleSpaceRemovalAdditionalTimes"]));
            }
            set {
                this["RunDoubleSpaceRemovalAdditionalTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveDoubleSpaces {
            get {
                return ((bool)(this["RemoveDoubleSpaces"]));
            }
            set {
                this["RemoveDoubleSpaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveCharacterReferences {
            get {
                return ((bool)(this["RemoveCharacterReferences"]));
            }
            set {
                this["RemoveCharacterReferences"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HandleTextBetweenParenthesis {
            get {
                return ((bool)(this["HandleTextBetweenParenthesis"]));
            }
            set {
                this["HandleTextBetweenParenthesis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PhrasesToPreserveFromParenthesis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PhrasesToPreserveFromParenthesis"]));
            }
            set {
                this["PhrasesToPreserveFromParenthesis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PhrasesToRemoveFromParenthesis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PhrasesToRemoveFromParenthesis"]));
            }
            set {
                this["PhrasesToRemoveFromParenthesis"] = value;
            }
        }
    }
}
